version: "3.8"

services:
    nginx:
        container_name: nginx
        #volumes:
        #    -wordpress:var/www/wordpress
        networks:
            - inception
        build: 
            context: requirements/nginx
            dockerfile: Dockerfile
        env_file:
            - .env
        ports :
        - "443:443"
        depends_on:
            - wordpress
        restart: on-failure

    mariadb:
        container_name: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file:
            - .env
        #volumes:
        #    -mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
            - "3306"
        
    wordpress:
        container_name: wordpress
        env_file: .env
        #volumes:
        #    -wordpress:/var/www/wordpress
        networks:
            - inception
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        expose:
            - "9000"

networks:
    inception:

